config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'home/authentication'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get '/top' => 'home#top'
  root 'home#top'
  #get '/articles/index' => 'articles#index'
  #get 'articles/new' => 'articles#new'
  resources :articles
  post '/articles' => 'articles#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
	validates :author, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only:[:show, :edit, :update, :destroy]
	before_action :authenticate_user!
	def index
		#いっぱいデータが入っているよ　の　複数形
		@articles = Article.all
	end

	def new
		@article = Article.new
		#ダミー　新規投稿だと教えている
	end
	
	def create
		#これから使うものだよ～
		@article = Article.new(article_params)
		#@article = Article.create(article_params)でも出来る。その場合.saveはいらない
    	if @article.save
    		redirect_to '/articles' #:action => index 
	    	#article_path(@article.id)
	    	#送信したらどっかに飛んで－　redirect_to
    	else
    		#書き込み失敗
    		render action: :new
    	end
	end

	def show
		@article = Article.find(params[:id])
	end

	def edit
		#showと一緒
	end

	def update
		if  @article.update(article_params)
    		redirect_to article_path(@article.id)
		else
			render action: :edit
		end
	end
	
	def destroy
    	@article.destroy
    	redirect_to articles_path
	end



	private
	def article_params
	  params.require(:article).permit(:title, :body, :author)
	end
	def set_article
      @article = Article.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def search_validate
    return false if !param_validate(:title, "タイトルを入力してください")
    return false if !param_validate(:body, "本文を入力してください")
    return false if !param_validate(:author, "著者を入力してください")
   # return false if !param_validate(:hour, "出発時間を入力してください")
    #return false if !param_validate(:minute, "出発時間を入力してください")
    #return false if !param_validate(:carType, "車種を入力してください")
    #return true
  end
  private
  def param_validate(key, message)
    if params[key] == ""
      flash[:alert] = message
      return false
    end

    return true
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/edit.html.erb
<div class="parent">
	<div class="header">
	</div>
	<div class="back-img2">
		<div class="center">
<h2>編集</h2>
<% if @article.errors.any? %>
  <div class="color"><h3>入力した内容にエラーが<%= @article.errors.count %>件あります</h3>
    <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul></div>
  <% end %>
  <br>
<%= form_for (@article) do |f| %>
 <div >タイトル<br>
 <%= f.text_field :title ,:size => "10x20"%></div>
 <div> 本文 <br>
 <%= f.text_area :body ,:size => "15x15"%></div>
 <div> 著者 <br>
 <%= f.text_field :author ,:size => "10x15"%></div>
<br>

<div><%# f.submit "送信" %>
	<input type="submit" value="" class="submit_btn">
</div>

<% end %>

<%= link_to "投稿一覧にもどる", :controller => "articles", :action => "index" %>
		</div>
	</div>
	<div class="footer">
		</div>
</div>

app/views/articles/index.html.erb
<html>
<head>
	<title>タイトル</title>
</head>
<body>
<div id="container2">
	<div class="back-img1">
		<div id="contents">
			<div class="parent">
				<div class="center">
	<h1>投稿一覧</h1>
	<% @articles.each do |article| %>
	  <p>タイトル</p>
   	<span><%= link_to article.title, "/articles/#{article.id}" %></span>
   	<br>
   	<%= link_to "編集", edit_article_path(article.id), class: "btn edit-btn" %>
   	<%= link_to "削除", article_path(article.id), method: :delete  %>
   	<br>
<% end %>
<br>
<br>
<%= link_to "新しく投稿", :controller => "articles", :action => "new", class: "btn new-btn" %>
				</div>
			</div>
		</div>
		<div id="footer">
		</div>
	</div>
</div>
</body>
</html>

app/views/articles/new.html.erb
<div class="back-img2">
	<div class="parent">
		<div class="center">
 <h1>新規投稿</h1>
 <%= form_for (@article) do |f| %>
 <div >タイトル<br>
 <%= f.text_field :title ,:size => "10x20"%></div>
 <div> 本文 <br>
 <%= f.text_area :body ,:size => "15x15"%></div>
 <div> 著者 <br>
 <%= f.text_field :author ,:size => "10x15"%></div>
<br>

<div><%# f.submit "送信" %>
	<input type="submit" value="" class="submit_btn">
</div>
<% end %>
<br>
<%= link_to "投稿一覧へ", :controller => "articles", :action => "index", class: "btn index-btn" %>
		</div>
	</div>
</div>

app/views/articles/show.html.erb
<div class="parent">
	<div class="header">
	</div>
	<div class="back-img2">
		<div class="center">
<h1>投稿詳細</h1>
<!--<h1>タイトル</h1>-->
<h2>「<%= @article.title %>」</h2>
<!--<h2>本文</h2>-->
<p class="body"><%= @article.body %></p>
<br>
<!--<h2>著者</h2>-->
<p>by <%= @article.author %></p>


<%= link_to "編集", edit_article_path(@article.id), class: "btn edit-btn" %><br>
<%= link_to "削除", article_path(@article.id), method: :delete, class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %>
<br>
<%= link_to "投稿一覧にもどる", :controller => "articles", :action => "index" %>
		</div>
	</div>
	<div class="footer">
		</div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/top.html.erb
	<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<HEAD>
<TITLE></TITLE>
</HEAD>
<BODY>
<!--<div class="center">-->

<div class="back-img">
<!--<%= image_tag 'dog.jpg' %> -->
<%= image_tag("dog.jpg", :class => "profile-img") %>
<h1>TOPページ</h1>
<h2">Natsuka Yabusaki</h2>

<%= link_to "投稿一覧へ", :controller => "articles", :action => "index" %>
<p>
	
</p>
</div>
<!--</div>-->
</BODY>
</HTML>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yabusaki</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if user_signed_in? %>
  	Logged in as <%= current_user.email %>
  	 <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
  	 <%= link_to 'プロフィール変更', edit_user_registration_path %>
    <% else %>
      <%= link_to "新規登録", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
  	<% end %>
    <%= yield %>
  </body>
</html>